// src/components/canvas/Canvas.svelte
<script>
  /**
   * VSMCanvas - Svelte Flow integration for VSM visualization
   *
   * This component wraps Svelte Flow and provides:
   * - Custom node types (StepNode for process visualization)
   * - Svelte stores integration for VSM data
   * - Pan/zoom controls and mini-map
   * - Node positioning and drag-to-update
   * - Connection visualization between steps
   */
  import {
    SvelteFlow,
    Background,
    Controls,
    MiniMap,
    MarkerType,
  } from '@xyflow/svelte'
  import '@xyflow/svelte/dist/style.css'

  import { vsmDataStore } from '../../stores/vsmDataStore.svelte.js'
  import { vsmUIStore } from '../../stores/vsmUIStore.svelte.js'
  import { simDataStore } from '../../stores/simulationDataStore.svelte.js'
  import { simControlStore } from '../../stores/simulationControlStore.svelte.js'
  import StepNode from './nodes/StepNode.svelte'

  const nodeTypes = {
    stepNode: StepNode,
  }

  const defaultEdgeOptions = {
    type: 'smoothstep',
    markerEnd: {
      type: MarkerType.ArrowClosed,
      width: 20,
      height: 20,
    },
    style: {
      strokeWidth: 2,
    },
  }

  // Derive nodes from store
  let nodes = $derived(
    vsmDataStore.steps.map((step) => ({
      id: step.id,
      type: 'stepNode',
      position: step.position,
      data: {
        ...step,
        simulationQueueSize: simControlStore.isRunning
          ? simDataStore.queueSizesByStepId[step.id]
          : undefined,
        isSimulationBottleneck: simDataStore.detectedBottlenecks.includes(step.id),
      },
      selected: step.id === vsmUIStore.selectedStepId,
    }))
  )

  // Derive edges from store
  let edges = $derived(
    vsmDataStore.connections.map((conn) => {
      const isSelected = conn.id === vsmUIStore.selectedConnectionId
      return {
        id: conn.id,
        source: conn.source,
        target: conn.target,
        type: 'smoothstep',
        animated: conn.type === 'rework',
        selected: isSelected,
        style: {
          stroke: isSelected ? '#3b82f6' : conn.type === 'rework' ? '#ef4444' : '#6b7280',
          strokeWidth: isSelected ? 3 : 2,
          strokeDasharray: conn.type === 'rework' ? '5,5' : 'none',
        },
        label: conn.type === 'rework' ? `${conn.reworkRate}% rework` : undefined,
        labelStyle: { fill: conn.type === 'rework' ? '#ef4444' : '#6b7280', fontSize: 10 },
      }
    })
  )

  function handleConnect(event) {
    const { source, target } = event.detail.connection
    vsmDataStore.addConnection(source, target)
  }

  function handleNodeDragStop(event) {
    const { node } = event.detail
    vsmDataStore.updateStepPosition(node.id, node.position)
  }

  function handleNodeClick(event) {
    const { node } = event.detail
    vsmUIStore.clearConnectionSelection()
    vsmUIStore.selectStep(node.id)
  }

  function handleNodeDoubleClick(event) {
    const { node } = event.detail
    vsmUIStore.selectStep(node.id)
    vsmUIStore.setEditing(true)
  }

  function handleEdgeClick(event) {
    const { edge } = event.detail
    vsmUIStore.selectConnection(edge.id)
  }

  function handlePaneClick() {
    vsmUIStore.clearSelection()
    vsmUIStore.clearConnectionSelection()
  }

  function handleKeyDown(event) {
    if (
      (event.key === 'Delete' || event.key === 'Backspace') &&
      vsmUIStore.selectedStepId
    ) {
      if (confirm('Delete this step?')) {
        vsmDataStore.deleteStep(vsmUIStore.selectedStepId)
      }
    }
  }

  function getNodeColor(node) {
    if (node.selected) return '#3b82f6'
    return '#9ca3af'
  }
</script>

<!-- svelte-ignore a11y_no_noninteractive_tabindex -->
<div
  class="w-full h-full"
  onkeydown={handleKeyDown}
  tabindex="0"
  data-testid="vsm-canvas"
>
  <SvelteFlow
    {nodes}
    {edges}
    {nodeTypes}
    {defaultEdgeOptions}
    fitView
    fitViewOptions={{ padding: 0.2 }}
    snapToGrid
    snapGrid={[10, 10]}
    onconnect={handleConnect}
    onnodedragstop={handleNodeDragStop}
    onnodeclick={handleNodeClick}
    onnodedoubleclick={handleNodeDoubleClick}
    onedgeclick={handleEdgeClick}
    onpaneclick={handlePaneClick}
  >
    <Background color="#e5e7eb" gap={20} />
    <Controls />
    <MiniMap
      nodeColor={getNodeColor}
      maskColor="rgba(0, 0, 0, 0.1)"
    />
  </SvelteFlow>
</div>

// src/components/canvas/Canvas.jsx
import { useCallback, useMemo } from 'react'
import ReactFlow, {
  Background,
  Controls,
  MiniMap,
  useNodesState,
  useEdgesState,
  addEdge,
  MarkerType,
} from 'reactflow'
import 'reactflow/dist/style.css'
import { useVsmStore } from '../../stores/vsmStore'
import StepNode from './nodes/StepNode'

const nodeTypes = {
  stepNode: StepNode,
}

const defaultEdgeOptions = {
  type: 'smoothstep',
  markerEnd: {
    type: MarkerType.ArrowClosed,
    width: 20,
    height: 20,
  },
  style: {
    strokeWidth: 2,
  },
}

function Canvas() {
  const {
    steps,
    connections,
    selectedStepId,
    selectedConnectionId,
    addConnection,
    deleteConnection,
    updateStepPosition,
    selectStep,
    setEditing,
    deleteStep,
    selectConnection,
    clearConnectionSelection,
  } = useVsmStore()

  const nodes = useMemo(
    () =>
      steps.map((step) => ({
        id: step.id,
        type: 'stepNode',
        position: step.position,
        data: step,
        selected: step.id === selectedStepId,
      })),
    [steps, selectedStepId]
  )

  const edges = useMemo(
    () =>
      connections.map((conn) => {
        const isSelected = conn.id === selectedConnectionId
        return {
          id: conn.id,
          source: conn.source,
          target: conn.target,
          type: 'smoothstep',
          animated: conn.type === 'rework',
          selected: isSelected,
          style: {
            stroke: isSelected ? '#3b82f6' : conn.type === 'rework' ? '#ef4444' : '#6b7280',
            strokeWidth: isSelected ? 3 : 2,
            strokeDasharray: conn.type === 'rework' ? '5,5' : 'none',
          },
          label: conn.type === 'rework' ? `${conn.reworkRate}% rework` : undefined,
          labelStyle: { fill: conn.type === 'rework' ? '#ef4444' : '#6b7280', fontSize: 10 },
        }
      }),
    [connections, selectedConnectionId]
  )

  const [reactFlowNodes, setNodes, onNodesChange] = useNodesState(nodes)
  const [reactFlowEdges, setEdges, onEdgesChange] = useEdgesState(edges)

  // Sync with store when steps/connections change
  useMemo(() => {
    setNodes(nodes)
  }, [nodes, setNodes])

  useMemo(() => {
    setEdges(edges)
  }, [edges, setEdges])

  const onConnect = useCallback(
    (params) => {
      addConnection(params.source, params.target)
    },
    [addConnection]
  )

  const onNodeDragStop = useCallback(
    (event, node) => {
      updateStepPosition(node.id, node.position)
    },
    [updateStepPosition]
  )

  const onNodeClick = useCallback(
    (event, node) => {
      event.stopPropagation()
      clearConnectionSelection()
      selectStep(node.id)
    },
    [selectStep, clearConnectionSelection]
  )

  const onNodeDoubleClick = useCallback(
    (event, node) => {
      event.stopPropagation()
      selectStep(node.id)
      setEditing(true)
    },
    [selectStep, setEditing]
  )

  const onEdgeClick = useCallback(
    (event, edge) => {
      event.stopPropagation()
      selectConnection(edge.id)
    },
    [selectConnection]
  )

  const onKeyDown = useCallback(
    (event) => {
      if (
        (event.key === 'Delete' || event.key === 'Backspace') &&
        selectedStepId
      ) {
        if (confirm('Delete this step?')) {
          deleteStep(selectedStepId)
        }
      }
    },
    [selectedStepId, deleteStep]
  )

  return (
    <div
      className="w-full h-full"
      onKeyDown={onKeyDown}
      tabIndex={0}
      data-testid="vsm-canvas"
    >
      <ReactFlow
        nodes={reactFlowNodes}
        edges={reactFlowEdges}
        onNodesChange={onNodesChange}
        onEdgesChange={onEdgesChange}
        onConnect={onConnect}
        onNodeDragStop={onNodeDragStop}
        onNodeClick={onNodeClick}
        onNodeDoubleClick={onNodeDoubleClick}
        onEdgeClick={onEdgeClick}
        nodeTypes={nodeTypes}
        defaultEdgeOptions={defaultEdgeOptions}
        fitView
        fitViewOptions={{ padding: 0.2 }}
        snapToGrid
        snapGrid={[10, 10]}
      >
        <Background color="#e5e7eb" gap={20} />
        <Controls />
        <MiniMap
          nodeColor={(node) => {
            if (node.selected) return '#3b82f6'
            return '#9ca3af'
          }}
          maskColor="rgba(0, 0, 0, 0.1)"
        />
      </ReactFlow>
    </div>
  )
}

export default Canvas
