// src/App.svelte
<script>
  import { SvelteFlowProvider } from '@xyflow/svelte'
  import { vsmDataStore } from './stores/vsmDataStore.svelte.js'
  import { vsmUIStore } from './stores/vsmUIStore.svelte.js'
  import Header from './components/ui/Header.svelte'
  import Canvas from './components/canvas/Canvas.svelte'
  import Sidebar from './components/ui/Sidebar.svelte'
  import MetricsDashboard from './components/metrics/MetricsDashboard.svelte'
  import WelcomeScreen from './components/ui/WelcomeScreen.svelte'
  import EditorPanel from './components/ui/EditorPanel.svelte'
  import SimulationPanel from './components/ui/SimulationPanel.svelte'
  import SimulationControls from './components/simulation/SimulationControls.svelte'

  // Reactive derived values from stores
  let hasVsm = $derived(vsmDataStore.id !== null)
  let selectedStepId = $derived(vsmUIStore.selectedStepId)
  let isEditing = $derived(vsmUIStore.isEditing)
  let selectedConnectionId = $derived(vsmUIStore.selectedConnectionId)
  let isEditingConnection = $derived(vsmUIStore.isEditingConnection)

  function handleCanvasClick() {
    if (isEditing || isEditingConnection) return
    vsmUIStore.clearSelection()
    vsmUIStore.clearConnectionSelection()
  }

  function handleCloseEditor() {
    vsmUIStore.setEditing(false)
    vsmUIStore.clearSelection()
  }

  function handleCloseConnectionEditor() {
    vsmUIStore.clearConnectionSelection()
  }
</script>

{#if !hasVsm}
  <WelcomeScreen />
{:else}
  <SvelteFlowProvider>
    <div class="h-screen flex flex-col bg-gray-100">
      <Header />
      <div class="flex-1 flex overflow-hidden">
        <Sidebar />
        <!-- svelte-ignore a11y_click_events_have_key_events a11y_no_noninteractive_element_interactions -->
        <main class="flex-1 flex flex-col" onclick={handleCanvasClick}>
          <SimulationControls />
          <div class="flex-1 relative">
            <Canvas />
          </div>
          <SimulationPanel />
          <MetricsDashboard />
        </main>
        <EditorPanel
          {selectedStepId}
          {isEditing}
          {selectedConnectionId}
          {isEditingConnection}
          onCloseEditor={handleCloseEditor}
          onCloseConnectionEditor={handleCloseConnectionEditor}
        />
      </div>
    </div>
  </SvelteFlowProvider>
{/if}

// src/App.jsx
import { useCallback } from 'react'
import { ReactFlowProvider } from 'reactflow'
import { useVsmStore } from './stores/vsmStore'
import Header from './components/ui/Header'
import Canvas from './components/canvas/Canvas'
import Sidebar from './components/ui/Sidebar'
import MetricsDashboard from './components/metrics/MetricsDashboard'
import WelcomeScreen from './components/ui/WelcomeScreen'
import StepEditor from './components/builder/StepEditor'
import ConnectionEditor from './components/builder/ConnectionEditor'

function App() {
  const {
    id,
    selectedStepId,
    isEditing,
    setEditing,
    clearSelection,
    selectedConnectionId,
    isEditingConnection,
    clearConnectionSelection,
  } = useVsmStore()

  const handleCanvasClick = useCallback(() => {
    if (isEditing || isEditingConnection) return
    clearSelection()
    clearConnectionSelection()
  }, [isEditing, isEditingConnection, clearSelection, clearConnectionSelection])

  const handleCloseEditor = useCallback(() => {
    setEditing(false)
    clearSelection()
  }, [setEditing, clearSelection])

  const handleCloseConnectionEditor = useCallback(() => {
    clearConnectionSelection()
  }, [clearConnectionSelection])

  if (!id) {
    return <WelcomeScreen />
  }

  return (
    <ReactFlowProvider>
      <div className="h-screen flex flex-col bg-gray-100">
        <Header />
        <div className="flex-1 flex overflow-hidden">
          <Sidebar />
          <main className="flex-1 flex flex-col" onClick={handleCanvasClick}>
            <div className="flex-1 relative">
              <Canvas />
            </div>
            <MetricsDashboard />
          </main>
          {selectedStepId && isEditing && (
            <StepEditor stepId={selectedStepId} onClose={handleCloseEditor} />
          )}
          {selectedConnectionId && isEditingConnection && (
            <ConnectionEditor
              connectionId={selectedConnectionId}
              onClose={handleCloseConnectionEditor}
            />
          )}
        </div>
      </div>
    </ReactFlowProvider>
  )
}

export default App
