// src/components/ui/Sidebar.svelte
<script>
  import { vsmDataStore } from '../../stores/vsmDataStore.svelte.js'
  import { vsmUIStore } from '../../stores/vsmUIStore.svelte.js'
  import {
    getTemplatesByCategory,
    CATEGORY_LABELS,
  } from '../../data/stepTemplates.js'
  import { STEP_TYPE_CONFIG } from '../../data/stepTypes.js'
  import { formatDuration } from '../../utils/calculations/metrics.js'

  let expandedCategory = $state(null)

  const templatesByCategory = getTemplatesByCategory()

  function handleAddStep() {
    const step = vsmDataStore.addStep('New Step')
    vsmUIStore.selectStep(step.id)
    vsmUIStore.setEditing(true)
  }

  function handleAddFromTemplate(template) {
    const step = vsmDataStore.addStep(template.name, {
      type: template.type,
      description: template.description,
      processTime: template.processTime,
      leadTime: template.leadTime,
      percentCompleteAccurate: template.percentCompleteAccurate,
      queueSize: template.queueSize,
      batchSize: template.batchSize,
    })
    vsmUIStore.selectStep(step.id)
    vsmUIStore.setEditing(true)
  }

  function toggleCategory(category) {
    expandedCategory = expandedCategory === category ? null : category
  }
</script>

<aside class="w-64 bg-white border-r border-gray-200 p-4 overflow-y-auto">
  <button
    onclick={handleAddStep}
    class="w-full flex items-center justify-center gap-2 px-4 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors font-medium"
    data-testid="add-step-button"
  >
    <span class="text-xl">+</span>
    <span>Add Step</span>
  </button>

  <div class="mt-6">
    <h2 class="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-3">
      Step Templates
    </h2>
    <div class="space-y-1">
      {#each Object.entries(templatesByCategory) as [category, templates] (category)}
        <div class="border border-gray-200 rounded-lg overflow-hidden">
          <button
            onclick={() => toggleCategory(category)}
            class="w-full px-3 py-2 text-left text-sm font-medium text-gray-700 hover:bg-gray-50 flex items-center justify-between"
          >
            <span>{CATEGORY_LABELS[category]}</span>
            <span class="text-gray-400">
              {expandedCategory === category ? '−' : '+'}
            </span>
          </button>
          {#if expandedCategory === category}
            <div class="border-t border-gray-200 bg-gray-50">
              {#each templates as template (template.id)}
                {@const config = STEP_TYPE_CONFIG[template.type]}
                <button
                  onclick={() => handleAddFromTemplate(template)}
                  class="w-full px-3 py-2 text-left hover:bg-gray-100 border-b border-gray-200 last:border-b-0"
                  data-testid="template-{template.id}"
                >
                  <div class="flex items-center gap-2">
                    <span>{config?.icon || '⚙️'}</span>
                    <span class="text-sm font-medium text-gray-700">
                      {template.name}
                    </span>
                  </div>
                  <div class="text-xs text-gray-500 mt-0.5 ml-6">
                    PT: {formatDuration(template.processTime)} | LT: {formatDuration(template.leadTime)}
                  </div>
                </button>
              {/each}
            </div>
          {/if}
        </div>
      {/each}
    </div>
  </div>

  <div class="mt-6">
    <h2 class="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-4">
      How to Use
    </h2>
    <div class="text-xs text-gray-600 space-y-3">
      <p>
        <strong>Add Step</strong> to create a new process step
      </p>
      <p>
        <strong>Click</strong> a step to select it
      </p>
      <p>
        <strong>Double-click</strong> a step to edit it
      </p>
      <p>
        <strong>Drag</strong> from handles to connect steps
      </p>
      <p>
        <strong>Delete</strong> key removes selected step
      </p>
    </div>
  </div>

  <div class="mt-8">
    <h2 class="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-4">
      Glossary
    </h2>
    <dl class="text-xs text-gray-600 space-y-2">
      <div>
        <dt class="font-semibold">PT (Process Time)</dt>
        <dd>Actual hands-on work time</dd>
      </div>
      <div>
        <dt class="font-semibold">LT (Lead Time)</dt>
        <dd>Total elapsed time including wait</dd>
      </div>
      <div>
        <dt class="font-semibold">%C&A</dt>
        <dd>Percent Complete & Accurate - quality passing to next step</dd>
      </div>
      <div>
        <dt class="font-semibold">Flow Efficiency</dt>
        <dd>PT ÷ LT - how much time is actual work vs waiting</dd>
      </div>
    </dl>
  </div>
</aside>

// src/components/ui/Sidebar.jsx
import { useCallback, useState } from 'react'
import PropTypes from 'prop-types'
import { useVsmStore } from '../../stores/vsmStore'
import {
  getTemplatesByCategory,
  CATEGORY_LABELS,
} from '../../data/stepTemplates'
import { STEP_TYPE_CONFIG } from '../../data/stepTypes'
import { formatDuration } from '../../utils/calculations/metrics'

function Sidebar() {
  const { addStep, selectStep, setEditing } = useVsmStore()
  const [expandedCategory, setExpandedCategory] = useState(null)

  const templatesByCategory = getTemplatesByCategory()

  const handleAddStep = useCallback(() => {
    const step = addStep('New Step')
    selectStep(step.id)
    setEditing(true)
  }, [addStep, selectStep, setEditing])

  const handleAddFromTemplate = useCallback(
    (template) => {
      const step = addStep(template.name, {
        type: template.type,
        description: template.description,
        processTime: template.processTime,
        leadTime: template.leadTime,
        percentCompleteAccurate: template.percentCompleteAccurate,
        queueSize: template.queueSize,
        batchSize: template.batchSize,
      })
      selectStep(step.id)
      setEditing(true)
    },
    [addStep, selectStep, setEditing]
  )

  const toggleCategory = useCallback((category) => {
    setExpandedCategory((prev) => (prev === category ? null : category))
  }, [])

  return (
    <aside className="w-64 bg-white border-r border-gray-200 p-4 overflow-y-auto">
      <button
        onClick={handleAddStep}
        className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors font-medium"
        data-testid="add-step-button"
      >
        <span className="text-xl">+</span>
        <span>Add Step</span>
      </button>

      <div className="mt-6">
        <h2 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-3">
          Step Templates
        </h2>
        <div className="space-y-1">
          {Object.entries(templatesByCategory).map(([category, templates]) => (
            <div key={category} className="border border-gray-200 rounded-lg overflow-hidden">
              <button
                onClick={() => toggleCategory(category)}
                className="w-full px-3 py-2 text-left text-sm font-medium text-gray-700 hover:bg-gray-50 flex items-center justify-between"
              >
                <span>{CATEGORY_LABELS[category]}</span>
                <span className="text-gray-400">
                  {expandedCategory === category ? '−' : '+'}
                </span>
              </button>
              {expandedCategory === category && (
                <div className="border-t border-gray-200 bg-gray-50">
                  {templates.map((template) => {
                    const config = STEP_TYPE_CONFIG[template.type]
                    return (
                      <button
                        key={template.id}
                        onClick={() => handleAddFromTemplate(template)}
                        className="w-full px-3 py-2 text-left hover:bg-gray-100 border-b border-gray-200 last:border-b-0"
                        data-testid={`template-${template.id}`}
                      >
                        <div className="flex items-center gap-2">
                          <span>{config?.icon || '⚙️'}</span>
                          <span className="text-sm font-medium text-gray-700">
                            {template.name}
                          </span>
                        </div>
                        <div className="text-xs text-gray-500 mt-0.5 ml-6">
                          PT: {formatDuration(template.processTime)} | LT:{' '}
                          {formatDuration(template.leadTime)}
                        </div>
                      </button>
                    )
                  })}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>

      <div className="mt-6">
        <h2 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-4">
          How to Use
        </h2>
        <div className="text-xs text-gray-600 space-y-3">
          <p>
            <strong>Add Step</strong> to create a new process step
          </p>
          <p>
            <strong>Click</strong> a step to select it
          </p>
          <p>
            <strong>Double-click</strong> a step to edit it
          </p>
          <p>
            <strong>Drag</strong> from handles to connect steps
          </p>
          <p>
            <strong>Delete</strong> key removes selected step
          </p>
        </div>
      </div>

      <div className="mt-8">
        <h2 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-4">
          Glossary
        </h2>
        <dl className="text-xs text-gray-600 space-y-2">
          <div>
            <dt className="font-semibold">PT (Process Time)</dt>
            <dd>Actual hands-on work time</dd>
          </div>
          <div>
            <dt className="font-semibold">LT (Lead Time)</dt>
            <dd>Total elapsed time including wait</dd>
          </div>
          <div>
            <dt className="font-semibold">%C&A</dt>
            <dd>Percent Complete & Accurate - quality passing to next step</dd>
          </div>
          <div>
            <dt className="font-semibold">Flow Efficiency</dt>
            <dd>PT ÷ LT - how much time is actual work vs waiting</dd>
          </div>
        </dl>
      </div>
    </aside>
  )
}

export default Sidebar
